### ISSUE TITLE
Нерабочая функциональная схема

### ISSUE THREAD

**Issue by amateomi** [IvanGrigorik/adaptive_lighting_system#2]
[Схема](https://github.com/IvanGrigorik/adaptive_lighting_system/blob/73e09de4b268bac2b7ae7f7c939cc67c967f1370/paper_work/pdf/%D0%A4%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F%20%D1%81%D1%85%D0%B5%D0%BC%D0%B0.drawio.pdf) очень странная и по всей видимости не рабочая

**Comment by IvanGrigorik** [comment]
Corrected
