### ISSUE TITLE
Кривая рамка

### ISSUE THREAD

**Issue by amateomi** [IvanGrigorik/adaptive_lighting_system#3]
[Рамка](https://github.com/IvanGrigorik/adaptive_lighting_system/blob/main/paper_work/pdf/%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%BD%D0%B0%D1%8F%20%D1%81%D1%85%D0%B5%D0%BC%D0%B0.pdf) в схемах должна быть ближе к правой стороне, а не к левой

**Comment by IvanGrigorik** [comment]
Corrected
